name: ndcube

channels:
    - conda-forge

dependencies:
    - python
    - astropy
    - Cython
    - matplotlib
    - numpy
    - openjpeg 
    - jinja2
    - scipy
    - requests
    - beautifulsoup4
    - sqlalchemy
    - scikit-image
    - pandas
    - nomkl
    - glymur
    - suds-jurko
    - sunpy
    - sphinx<1.7
    - sphinx==1.6.7
    - pip:
      - sunpy-sphinx-theme
