name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  # These will need to be changed  for your project.
  CI_BUILD_URL: "https://dev.azure.com/sunpy/ndcube/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"

# These resources need to be setup on the Azure Pipeline website
# as a service connection (if it has not been already).
resources:
  repositories:
  - repository: sunpy
    type: github
    endpoint: sunpy
    name: sunpy/azure-pipelines-template
    ref: pypi_no_wheels

trigger:
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:

- template: run-tox-env.yml@sunpy
  parameters:
    name: pycodestyle
    os: linux
    tox: pycodestyle --

- template: run-tox-env.yml@sunpy
  parameters:
    name: Linux_37_offline
    os: linux
    tox: py37-offline --

- template: run-tox-env.yml@sunpy
  parameters:
    name: Windows_36_offline
    os: windows
    tox: py36-offline --

- template: run-tox-env.yml@sunpy
  parameters:
    name: macOS_37_online
    os: macos
    tox: py37-online --

- template: run-tox-env.yml@sunpy
  parameters:
    name: Linux_37_astropydev
    os: linux
    tox: py37-astropydev --

- template: run-tox-env.yml@sunpy
  parameters:
    name: Linux_37_sunpydev
    os: linux
    tox: py37-sunpydev --

- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  - template: publish-pypi.yml@sunpy
    parameters:
      external_feed: 'PyPI'
      targets:
        - sdist
      dependsOn: [Linux_37_offline,Windows_36_offline,macOS_37_online]
